from __future__ import annotations

from app.web.backtest_common import (
    EQUAL_WEIGHT_PRESETS,
    DUAL_MOMENTUM_PRESETS,
    GLOBAL_RELATIVE_STRENGTH_PRESETS,
    GTAA_PRESETS,
    QUALITY_BROAD_PRESETS,
    QUALITY_STRICT_PRESETS,
    RISK_PARITY_PRESETS,
    VALUE_STRICT_PRESETS,
)

__all__ = [
    "DUAL_MOMENTUM_PRESETS",
    "EQUAL_WEIGHT_PRESETS",
    "GLOBAL_RELATIVE_STRENGTH_PRESETS",
    "GTAA_PRESETS",
    "QUALITY_BROAD_PRESETS",
    "QUALITY_STRICT_PRESETS",
    "RISK_PARITY_PRESETS",
    "VALUE_STRICT_PRESETS",
]
